Name:           ros-melodic-uuv-gazebo-ros-plugins
Version:        0.6.12
Release:        0%{?dist}
Summary:        ROS uuv_gazebo_ros_plugins package

Group:          Development/Libraries
License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-gazebo-dev
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf2
Requires:       ros-melodic-tf2-ros
Requires:       ros-melodic-uuv-gazebo-plugins
Requires:       ros-melodic-uuv-gazebo-ros-plugins-msgs
Requires:       ros-melodic-visualization-msgs
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-gazebo-dev
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf2
BuildRequires:  ros-melodic-tf2-ros
BuildRequires:  ros-melodic-uuv-gazebo-plugins
BuildRequires:  ros-melodic-uuv-gazebo-ros-plugins-msgs
BuildRequires:  ros-melodic-visualization-msgs
BuildRequires:  ros-melodic-xacro

%description
UUV Simulator's extended ROS plugins for generation of the necessary ROS
services and topics during the simulation.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu May 30 2019 Musa Morena Marcusso Manhaes <musa.marcusso@de.bosch.com> - 0.6.12-0
- Autogenerated by Bloom

* Tue Mar 12 2019 Musa Morena Marcusso Manhaes <musa.marcusso@de.bosch.com> - 0.6.10-0
- Autogenerated by Bloom

